# Generated by Django 3.0.2 on 2020-02-01 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='next_allowed_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 15, 4, 1, 108549)),
        ),
    ]
